# Generated by Django 4.0.5 on 2022-06-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('role', models.TextField()),
                ('type', models.TextField()),
                ('description', models.TextField()),
                ('difficulty', models.TextField()),
                ('card_portrait', models.TextField()),
                ('franchise', models.TextField()),
                ('href', models.TextField()),
            ],
            options={
                'ordering': ['franchise'],
            },
        ),
    ]
